# Generated by Django 4.1.3 on 2022-12-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTicket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Soluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='asunto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
